# Registration POST Request
POST http://localhost:3200/user/register
Content-Type: application/json

{
    "name":"rishabh parashar",
    "username":"theGangooWarGod",
    "password":"rishabh@123",
    "repeatPassword":"rishabh@123"
}

###

# Login POST Request
POST http://localhost:3200/user/login
Content-Type: application/json

{
    "username":"theGangooWarGod",
    "password":"rishabh@123"
}